import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
          '*.json',
          '/_vercel/',
          '/404',
          '/500',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/_next/',
          '/admin/',
          '/private/',
        ],
      },
      {
        userAgent: 'GPTBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'ChatGPT-User', 
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'CCBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'ClaudeBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'Anthropic-AI',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'PerplexityBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'YouBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'Google-Extended',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'Applebot-Extended',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'Meta-ExternalAgent',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'OAI-SearchBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'DeepseekBot',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'Cohere-AI',
        allow: [
          '/',
          '/column/',
          '/column/*',
          '/services/',
          '/services/*',
          '/company',
          '/features',
          '/faq',
          '/materials',
          '/diagnosis',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
          '/contact',
          '/newsletter',
          '/privacy',
          '/terms',
        ],
      },
      {
        userAgent: 'AdsBot-Google',
        disallow: '/',
      },
      {
        userAgent: 'Twitterbot',
        disallow: [
          '/api/',
          '/admin/',
          '/private/',
        ],
      },
      {
        userAgent: 'facebookexternalhit',
        disallow: [
          '/api/',
          '/admin/', 
          '/private/',
        ],
      },
    ],
    sitemap: 'https://gyaku-ten.jp/sitemap.xml',
    host: 'https://gyaku-ten.jp',
  }
}